import React,{useState,useEffect,useCallback,useContext} from 'react';
import {Link} from 'react-router-dom';import api from '../services/api';import AuthContext from '../state/AuthContext';
const money=v=>'$'+Number(v||0).toLocaleString(undefined,{maximumFractionDigits:2});
export default function DashboardPage(){
 const {user}=useContext(AuthContext);const [myListings,setMyListings]=useState([]),[bookings,setBookings]=useState([]),[incoming,setIncoming]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[busyId,setBusyId]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');const results=await Promise.allSettled([api.get('/listings/mylistings'),api.get('/bookings/mine'),api.get('/bookings/incoming')]);if(results[0].status==='fulfilled')setMyListings(results[0].value.data||[]);else setError('Could not load your listings.');if(results[1].status==='fulfilled')setBookings(results[1].value.data||[]);else setError(old=>old?old+' Buyer booking history unavailable.':'Buyer booking history unavailable.');if(results[2].status==='fulfilled')setIncoming(results[2].value.data||[]);else setIncoming([]);setLoading(false);},[]);
 useEffect(()=>{load();},[load]);
 const remove=async id=>{if(!window.confirm('Delete this listing? This cannot be undone.'))return;try{await api.delete('/listings/'+id);setMessage('Listing deleted.');await load();}catch(e){setError(e?.response?.data?.message||'Failed to delete listing.');}};
 const updateBooking=async(id,status)=>{try{setBusyId(id);setError('');setMessage('');await api.patch('/bookings/'+id+'/status',{status});setMessage(status==='accepted'?'Request accepted. The buyer can now proceed to payment once checkout is enabled.':status==='rejected'?'Booking request declined.':'Booking request cancelled.');await load();}catch(e){setError(e?.response?.data?.message||'Could not update booking.');}finally{setBusyId('');}};
 const requestPayment=async id=>{try{setBusyId(id);const {data}=await api.post('/bookings/'+id+'/payment/order');setMessage(data.message||'Payment checkout is not ready.');}catch(e){setError(e?.response?.data?.message||'Payment checkout is not configured yet.');}finally{setBusyId('');}};
 const capacity=myListings.reduce((s,x)=>s+Number(x.availableCBM||0),0),spend=bookings.reduce((s,x)=>s+Number(x.amount||0),0);
 const actions=b=><div className="booking-workflow-actions">{b.status==='pending'&&String(b.seller?._id||b.seller)===String(user?._id)&&<><button className="booking-action-btn" disabled={busyId===b._id} onClick={()=>updateBooking(b._id,'accepted')}>Accept</button><button className="booking-action-btn danger" disabled={busyId===b._id} onClick={()=>updateBooking(b._id,'rejected')}>Decline</button></>}{['pending','accepted'].includes(b.status)&&String(b.buyer?._id||b.buyer)===String(user?._id)&&<button className="booking-action-btn danger" disabled={busyId===b._id} onClick={()=>updateBooking(b._id,'cancelled')}>Cancel</button>}{b.status==='accepted'&&b.paymentStatus!=='paid'&&String(b.buyer?._id||b.buyer)===String(user?._id)&&<button className="booking-action-btn" disabled={busyId===b._id} onClick={()=>requestPayment(b._id)}>{busyId===b._id?'Working…':'Pay & confirm'}</button>}<Link className="booking-action-btn" to={'/messages/'+b._id}>Message</Link>{b.paymentStatus==='paid'&&<Link className="booking-action-btn" to={'/invoice/'+b._id}>Invoice</Link>}</div>;
 return <div className="dashboard-page"><section className="dashboard-hero glass-panel"><div><span className="eyebrow">YOUR WORKSPACE</span><h1>Welcome back, {user?.name||'there'}.</h1><p>Manage listings, incoming requests, conversations and reservations.</p></div><Link to="/create-listing" className="btn">+ List new space</Link></section>
 {error&&<p className="message-error">{error}</p>}{message&&<p className="message-success">{message}</p>}
 <section className="dashboard-kpi-grid"><div className="dashboard-kpi glass-panel"><span>My listings</span><strong>{myListings.length}</strong><small>Published spaces</small></div><div className="dashboard-kpi glass-panel"><span>Listed capacity</span><strong>{capacity.toLocaleString()} CBM</strong><small>Remaining listed capacity</small></div><div className="dashboard-kpi glass-panel"><span>Bookings made</span><strong>{bookings.length}</strong><small>Buyer booking history</small></div><div className="dashboard-kpi glass-panel"><span>Incoming requests</span><strong>{incoming.filter(x=>x.status==='pending').length}</strong><small>Waiting for your response</small></div></section>
 <section className="dashboard-section glass-panel"><div className="dashboard-section-heading"><div><span className="eyebrow">SELLER WORKSPACE</span><h2>Incoming booking requests</h2></div><span className="admin-count">{incoming.length} total</span></div>{loading?<p>Loading requests…</p>:incoming.length===0?<div className="dashboard-empty"><h3>No requests yet</h3><p>When a buyer requests your capacity, it will appear here.</p></div>:<div className="admin-table-wrap"><table className="listings-table"><thead><tr><th>Route</th><th>Buyer</th><th>Quantity</th><th>Amount</th><th>Status</th><th>Actions</th></tr></thead><tbody>{incoming.map(b=><tr key={b._id}><td>{b.listing?<Link to={'/listing/'+b.listing._id}>{b.listing.origin} → {b.listing.destination}</Link>:'Listing unavailable'}</td><td>{b.buyer?.companyName||b.buyer?.name||'Buyer'}</td><td>{b.quantityCBM} CBM</td><td>{money(b.amount)}</td><td><span className={'role-pill '+b.status}>{b.status}</span><small className="booking-note"> · {b.paymentStatus}</small></td><td>{actions(b)}</td></tr>)}</tbody></table></div>}</section>
 <section className="dashboard-section glass-panel"><div className="dashboard-section-heading"><div><span className="eyebrow">SUPPLY</span><h2>My listings</h2></div><span className="admin-count">{myListings.length} total</span></div>{loading?<p>Loading dashboard…</p>:myListings.length===0?<div className="dashboard-empty"><h3>No listings yet</h3><p>Publish your first available container space to get started.</p><Link className="btn" to="/create-listing">Create listing</Link></div>:<div className="admin-table-wrap"><table className="listings-table"><thead><tr><th>Route</th><th>Departure</th><th>Capacity</th><th>Price</th><th>Actions</th></tr></thead><tbody>{myListings.map(x=><tr key={x._id}><td><Link to={'/listing/'+x._id}>{x.origin} → {x.destination}</Link></td><td>{new Date(x.departureDate).toLocaleDateString()}</td><td>{x.availableCBM} CBM · {Number(x.availableWeightKG).toLocaleString()} kg</td><td>{money(x.pricePerCBM)}/CBM</td><td className="dashboard-actions"><Link className="admin-action" to={'/listing/'+x._id}>View</Link><button className="btn-delete" onClick={()=>remove(x._id)}>Delete</button></td></tr>)}</tbody></table></div>}</section>
 <section className="dashboard-section glass-panel"><div className="dashboard-section-heading"><div><span className="eyebrow">DEMAND</span><h2>My bookings</h2></div><span className="admin-count">{bookings.length} bookings</span></div>{loading?<p>Loading booking history…</p>:bookings.length===0?<div className="dashboard-empty"><h3>No bookings yet</h3><p>When you request a space, its status and next steps appear here.</p><Link className="btn btn-outline" to="/find-space">Explore spaces</Link></div>:<div className="admin-table-wrap"><table className="listings-table"><thead><tr><th>Route</th><th>Seller</th><th>Quantity</th><th>Amount</th><th>Status</th><th>Next steps</th></tr></thead><tbody>{bookings.map(b=><tr key={b._id}><td>{b.listing?<Link to={'/listing/'+b.listing._id}>{b.listing.origin} → {b.listing.destination}</Link>:'Listing unavailable'}</td><td>{b.seller?.companyName||b.seller?.name||b.listing?.companyName||'—'}</td><td>{b.quantityCBM} CBM</td><td>{money(b.amount)}</td><td><span className={'role-pill '+b.status}>{b.status}</span><small className="booking-note"> · {b.paymentStatus}</small></td><td>{actions(b)}</td></tr>)}</tbody></table></div>}</section>
 </div>;
}