import React,{useEffect,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import api from '../services/api';
export default function SellerProfilePage(){
 const {id}=useParams();const [profile,setProfile]=useState(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 useEffect(()=>{let active=true;api.get('/users/'+id).then(({data})=>{if(active)setProfile(data);}).catch(e=>{if(active)setError(e?.response?.data?.message||'Could not load company profile.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[id]);
 if(loading)return <section className="listing-details-state"><p>Loading company profile…</p></section>;
 if(error||!profile)return <section className="listing-details-state"><h1>Company not found</h1><p>{error}</p><Link className="btn" to="/find-space">Back to marketplace</Link></section>;
 const {user,listings,reviews,averageRating,reviewCount}=profile;
 return <section className="seller-page">
  <Link className="back-link" to="/find-space">← Back to marketplace</Link>
  <header className="seller-hero glass-panel"><div className="seller-avatar seller-avatar-large">{(user.companyName||'S').slice(0,1).toUpperCase()}</div><div className="seller-hero-info"><span className="eyebrow">SHIPSPACE COMPANY PROFILE</span><h1>{user.companyName}</h1><p>Managed by {user.name}</p><div className="seller-profile-badges"><span className={'role-pill '+user.verificationStatus}>{user.verificationStatus==='verified'?'✓ Verified company':user.verificationStatus==='pending'?'Verification pending':'Not verified'}</span><span className="role-pill">{user.subscriptionTier} plan</span><span className="role-pill">{averageRating?'★ '+averageRating+' / 5':'No rating yet'} · {reviewCount} reviews</span></div><small>Member since {new Date(user.createdAt).toLocaleDateString(undefined,{month:'long',year:'numeric'})}</small></div></header>
  <div className="seller-profile-stats"><div className="dashboard-kpi glass-panel"><span>Published listings</span><strong>{listings.length}</strong></div><div className="dashboard-kpi glass-panel"><span>Reviews received</span><strong>{reviewCount}</strong></div><div className="dashboard-kpi glass-panel"><span>Average rating</span><strong>{averageRating?'★ '+averageRating:'—'}</strong></div></div>
  <div className="dashboard-section glass-panel"><div className="dashboard-section-heading"><div><span className="eyebrow">AVAILABLE CAPACITY</span><h2>Company listings</h2></div><span className="admin-count">{listings.length} listings</span></div>
   {!listings.length?<p>This company has no active listings yet.</p>:<div className="listings-grid">{listings.map(item=><article className="listing-card" key={item._id}><div className="listing-accent"/><div className="card-header"><div><span className="route-label">AVAILABLE ROUTE</span><h3>{item.origin} <span>→</span> {item.destination}</h3></div><span className="price">${Number(item.pricePerCBM).toLocaleString()}<small>/CBM</small></span></div><div className="card-body"><p><strong>Departure</strong><span>{new Date(item.departureDate).toLocaleDateString()}</span></p><p><strong>Capacity</strong><span>{item.availableCBM} CBM · {Number(item.availableWeightKG).toLocaleString()} kg</span></p><p><strong>Cargo</strong><span className="cargo-badge">{item.cargoType}</span></p></div><div className="card-footer"><Link className="btn" to={'/listing/'+item._id}>View listing</Link></div></article>)}</div>}
  </div>
  <div className="dashboard-section glass-panel"><div className="dashboard-section-heading"><div><span className="eyebrow">BUYER FEEDBACK</span><h2>Recent reviews</h2></div></div>{!reviews?.length?<p>No reviews have been posted for this company yet.</p>:reviews.map(review=><article className="review-item" key={review._id}><div><strong>{review.reviewer?.companyName||review.reviewer?.name||'ShipSpace user'}</strong><span className="review-stars">{'★'.repeat(review.rating)}{'☆'.repeat(5-review.rating)}</span></div><p>{review.comment}</p><small>{new Date(review.createdAt).toLocaleDateString()}</small></article>)}</div>
 </section>;
}